OC.L10N.register("files_external",{
    "Fetching request tokens failed. Verify that your app key and secret are correct.": "Mã thông báo yêu cầu đang tìm thất bại. Xác minh rằng chìa khóa và bí mật ứng dụng của bạn là chính xác.",
    "Fetching access tokens failed. Verify that your app key and secret are correct.": "Mã thông báo truy cập đang tìm thất bại. Xác minh rằng chìa khóa và bí mật ứng dụng của bạn là chính xác.",
    "Please provide a valid app key and secret.": "Vui lòng cung cấp một chìa khóa và bí mật ứng dụng hợp lệ.",
    "Step 1 failed. Exception: %s": "Bước 1 thất bại. Ngoại lệ: %s",
    "Step 2 failed. Exception: %s": "Bước 2 thất bại. Ngoại lệ: %s",
    "External storage": "Bộ nhớ ngoài",
    "Dropbox App Configuration": "Cấu hình ứng dụng Dropbox",
    "Google Drive App Configuration": "Cấu hình ứng dụng Google Drive",
    "Personal": "Cá nhân",
    "System": "Hệ thống",
    "Grant access": "Cấp phép truy cập",
    "Error configuring OAuth1": "Lỗi cấu hình OAuth1",
    "Error configuring OAuth2": "Lỗi cấu hình OAuth2",
    "Generate keys": "Tạo chìa khóa",
    "Error generating key pair": "Lỗi tạo cặp chìa khóa",
    "All users. Type to select user or group.": "Tất cả người dùng. Đánh chữ để chọn người dùng hoặc nhóm.",
    "(group)": "(nhóm)",
    "Compatibility with Mac NFD encoding (slow)": "Tương thích với mã hóa Mac NFD (chậm)",
    "Admin defined": "Quản trị viên xác nhận",
    "Saved": "Đã lưu",
    "Empty response from the server": "Hồi đáp rỗng từ máy chủ",
    "Couldn't access. Please logout and login to activate this mount point": "Không thể truy cập. Vui lòng đăng xuất và đăng nhập lại để kích hoạt điểm gắn kết này",
    "Couldn't get the information from the ownCloud server: {code} {type}": "Không thể lấy thông tin từ máy chủ ownCloud: {code} {type}",
    "Couldn't get the list of external mount points: {type}": "Không thể lấy danh sách điểm gắn kết ngoài: {type}",
    "There was an error with message:": "Xảy ra lỗi với tin nhắn:",
    "External mount error": "Lỗi gắn kết ngoài",
    "external-storage": "Bộ nhớ ngoài",
    "Couldn't get the list of Windows network drive mount points: empty response from the server": "Không thể lấy danh sách điểm gắn kết ổ cứng làm việc Windows: hồi đáp rỗng từ máy chủ",
    "Some of the configured external mount points are not connected. Please click on the red row(s) for more information": "Một số điểm gắn kết ngoài được cấu hình không thể kết nối được. Vui lòng nhấp vào dòng màu đỏ để biết thêm thông tin",
    "Please enter the credentials for the {mount} mount": "Vui lòng nhập thông tin cho gắn kết {mount}",
    "Username": "Tên người dùng",
    "Password": "Mật khẩu",
    "Credentials saved": "Thông tin đã được lưu",
    "Credentials saving failed": "Lưu thông tin thất bại",
    "Credentials required": "Thông tin được yêu cầu",
    "Save": "Lưu   ",
    "Storage with id \"%i\" not found": "Không tìm thấy bộ nhớ với id \"%i\"",
    "Invalid backend or authentication mechanism class": "Phụ trợ hoặc lớp cơ chế xác thực không hợp lệ ",
    "Invalid mount point": "Điểm gắn kết không hợp lệ",
    "Objectstore forbidden": "Kho vật phẩm bị cấm",
    "Invalid storage backend \"%s\"": "Phụ trợ bộ nhớ \"%s\" không hợp lệ",
    "Not permitted to use backend \"%s\"": "Không cho phép dùng phụ trợ \"%s\"",
    "Not permitted to use authentication mechanism \"%s\"": "Không cho phép dùng cơ chế xác thực \"%s\"",
    "Unsatisfied backend parameters": "Thông số phụ trợ không được đáp ứng ",
    "Unsatisfied authentication mechanism parameters": "Thông số cơ chế xác thực không được đáp ứng ",
    "Insufficient data: %s": "Dữ liệu không đầy đủ: %s",
    "%s": "%s",
    "Storage with id \"%i\" is not user editable": "Bộ nhớ với id \"%i\" không cho người dùng chỉnh sửa",
    "Access key": "Chìa khóa truy cập",
    "Secret key": "Chìa khóa bí mật",
    "Builtin": "Gắn liền",
    "None": "Không chọn",
    "OAuth1": "OAuth1",
    "App key": "Chìa khóa ứng dụng",
    "App secret": "Bí mật ứng dụng",
    "OAuth2": "OAuth2",
    "Client ID": "Client ID",
    "Client secret": "Bí mật khách ",
    "OpenStack": "OpenStack",
    "Tenant name": "Tên người thuê",
    "Identity endpoint URL": "URL điểm cuối danh tính",
    "Rackspace": "Rackspace",
    "API key": "Chìa khóa API",
    "Username and password": "Tên người dùng và mật khẩu",
    "Log-in credentials, save in session": "Thông tin đăng nhập, lưu theo phiên",
    "RSA public key": "Chìa khóa cộng đồng RSA",
    "Public key": "Chìa khóa cộng đồng",
    "Amazon S3": "Amazon S3",
    "Bucket": "Thùng nén",
    "Hostname": "Máy chủ",
    "Port": "Cổng",
    "Region": "Vùng",
    "Enable SSL": "Kích hoạt SSL",
    "Enable Path Style": "Kích hoạt loại đường dẫn",
    "WebDAV": "WebDAV",
    "URL": "URL",
    "Remote subfolder": "Thư mục phụ từ xa",
    "Secure https:\/\/": "Bảo đảm https:\/\/",
    "Dropbox": "Dropbox",
    "FTP": "FTP",
    "Host": "Máy chủ",
    "Secure ftps:\/\/": "Bảo đảm ftps:\/\/",
    "Google Drive": "Google Drive",
    "Local": "Cục bộ",
    "Location": "Vị trí",
    "ownCloud": "ownCloud",
    "SFTP": "SFTP",
    "Root": "Root",
    "SFTP with secret key login": "SFTP với chìa khóa đăng nhập bí mật",
    "SMB \/ CIFS": "SMB \/ CIFS",
    "Share": "Chia sẻ",
    "Domain": "Miền",
    "SMB \/ CIFS using OC login": "SMB \/ CIFS dùng đăng nhập OC",
    "Username as share": "Tên người dùng khi chia sẻ",
    "OpenStack Object Storage": "Bộ nhớ đối tượng OpenStack",
    "Service name": "Tên dịch vụ",
    "Request timeout (seconds)": "Quá thời gian yêu cầu (giây)",
    "<b>Note:<\/b>": "<b>Lưu ý:<\/b>",
    "<b>Note:<\/b> The cURL support in PHP is not enabled or installed. Mounting of %s is not possible. Please ask your system administrator to install it.": "<b>Lưu ý:<\/b> Hỗ trợ cURL trong PHP không được bật hoặc cài đặt. Không thể gắn kết %s. Hãy yêu cầu quản trị hệ thống của bạn để cài đặt nó.",
    "<b>Note:<\/b> The FTP support in PHP is not enabled or installed. Mounting of %s is not possible. Please ask your system administrator to install it.": "<b>Lưu ý:<\/b> Hỗ trợ FTP trong PHP không được bật hoặc cài đặt. Không thể gắn kết %s. Hãy yêu cầu quản trị hệ thống của bạn để cài đặt nó.",
    "<b>Note:<\/b> \"%s\" is not installed. Mounting of %s is not possible. Please ask your system administrator to install it.": "<b>Lưu ý:<\/b> \"%s\" không được cài đặt. Không thể gắn kết %s. Hãy yêu cầu quản trị hệ thống của bạn để cài đặt nó.",
    "No external storage configured": "Không có bộ nhớ ngoài được cấu hình",
    "You can add external storages in the personal settings": "Bạn có thể thêm bộ nhớ ngoài trong phần thiết lập cá nhân",
    "Name": "Tên",
    "Storage type": "Loại bộ nhớ",
    "Scope": "Phạm vi",
    "Enable encryption": "Cho phép mã hóa",
    "Enable previews": "Cho phép xem trước",
    "Enable sharing": "Cho phép chia sẻ",
    "Check for changes": "Kiểm tra thay đổi",
    "Never": "Không bao giờ",
    "Once every direct access": "Một lần tất cả hướng truy cập",
    "External Storage": "Bộ nhớ ngoài",
    "Folder name": "Tên thư mục",
    "Authentication": "Xác thực",
    "Configuration": "Cấu hình",
    "Available for": "Sẵn sàng cho",
    "Add storage": "Thêm bộ nhớ",
    "Advanced settings": "Thiết lập nâng cao",
    "Delete": "Xóa",
    "Allow users to mount external storage": "Cho phép người dùng gắn kết bộ nhớ ngoài"
},"nplurals=1; plural=0;");