OC.L10N.register("encryption",{
    "Missing recovery key password": "Thiếu chìa khóa mật khẩu khôi phục ",
    "Please repeat the recovery key password": "Vui lòng lặp lại chìa khóa mật khẩu khôi phục chính",
    "Repeated recovery key password does not match the provided recovery key password": "Lặp lại chìa khóa mật khẩu khôi phục không khớp với chìa khóa mật khẩu khôi phục trước",
    "Recovery key successfully enabled": "Chìa khóa khôi phục được kích hoạt thành công",
    "Could not enable recovery key. Please check your recovery key password!": "Không thể kích hoạt chìa khóa khôi phục. Vui lòng kiểm tra chìa khóa mật khẩu khôi phục!",
    "Recovery key successfully disabled": "Chìa khóa khôi phục bị vô hiệu thành công",
    "Could not disable recovery key. Please check your recovery key password!": "Không thể vô hiệu chìa khóa khôi phục. Vui lòng kiểm tra chìa khóa mật khẩu khôi phục!",
    "Missing parameters": "Thiếu các thông số",
    "Please provide the old recovery password": "Vui lòng cung cấp mật khẩu khôi phục cũ",
    "Please provide a new recovery password": "Vui lòng cung cấp mật khẩu khôi phục mới",
    "Please repeat the new recovery password": "Vui lòng lặp lại mật khẩu khôi phục mới",
    "Password successfully changed.": "Mật khẩu thay đổi thành công.",
    "Could not change the password. Maybe the old password was not correct.": "Không thể thay đổi mật khẩu. Có thể mật khẩu cũ không đúng.",
    "Recovery Key disabled": "Chìa khóa khôi phục bị vô hiệu",
    "Recovery Key enabled": "Chìa khóa khôi phục được kích hoạt",
    "Could not enable the recovery key, please try again or contact your administrator": "Không thể kích hoạt chìa khóa khôi phục, vui lòng thử lại hoặc liên hệ quản trị viên của bạn",
    "Could not update the private key password.": "Không thể cập nhật chìa khóa mật khẩu riêng.",
    "The old password was not correct, please try again.": "Mật khẩu cũ không đúng, vui lòng thử lại.",
    "The current log-in password was not correct, please try again.": "Mật khẩu đăng nhập gần đây không đúng, vui lòng thử lại.",
    "Private key password successfully updated.": "Chìa khóa mật khẩu riêng được cập nhật thành công.",
    "You need to migrate your encryption keys from the old encryption (ownCloud <= 8.0) to the new one. Please run 'occ encryption:migrate' or contact your administrator": "Bạn cần phải di chuyển các chài khóa mã hóa từ mật mã cũ (ownCloud < = 8,0) sang mới. Vui lòng chạy ' mã hóa occ: di chuyển ' hoặc liên hệ với quản trị viên của bạn",
    "Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.": "Chìa khóa riêng không hợp lệ với ứng dụng mã hóa. Xin vui lòng cập nhật chìa khóa mật khẩu riêng của bạn trong phần thiết lập cá nhân của bạn để khôi phục lại quyền truy cập vào các tập tin được mã hóa.",
    "Encryption App is enabled but your keys are not initialized, please log-out and log-in again": "Ứng dụng mã hóa được kích hoạt nhưng chìa khóa của bạn không được khởi tạo, xin vui lòng đăng xuất và đăng nhập lại",
    "Encryption App is enabled and ready": "Ứng dụng mã hóa đã được kích hoạt và sẵn sàng sử dụng",
    "Bad Signature": "Giao diện xấu",
    "Missing Signature": "Thiếu giao diện",
    "one-time password for server-side-encryption": "mật khẩu một lần cho mã hóa máy chủ",
    "Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.": "Không thể giải mã tập tin này, có lẽ đây là một tập tin được chia sẻ. Hãy yêu cầu chủ sở hữu tập tin để chia sẻ lại tập tin với bạn.",
    "Can not read this file, probably this is a shared file. Please ask the file owner to reshare the file with you.": "Không thể đọc được tập tin này, có lẽ đây là một tập tin được chia sẻ. Hãy yêu cầu chủ sở hữu tập tin để chia sẻ lại tập tin với bạn.",
    "Hey there,the admin enabled server-side-encryption. Your files were encrypted using the password '%s'. Please login to the web interface, go to the section 'ownCloud basic encryption module' of your personal settings and update your encryption password by entering this password into the 'old log-in password' field and your current login-password.": true,
    "The share will expire on %s.": "Chia sẻ sẽ hết hạn vào %s.",
    "Cheers!": "Chúc mừng!",
    "Hey there,<br><br>the admin enabled server-side-encryption. Your files were encrypted using the password <strong>%s<\/strong>.<br><br>Please login to the web interface, go to the section \"ownCloud basic encryption module\" of your personal settings and update your encryption password by entering this password into the \"old log-in password\" field and your current login-password.<br><br>": true,
    "Encrypt the home storage": "Mã hóa bộ nhớ máy",
    "Enabling this option encrypts all files stored on the main storage, otherwise only files on external storage will be encrypted": "Kích hoạt tùy chọn này sẽ mã hóa tất cả các tập tin được lưu trữ trong bộ nhớ chính, nếu không chỉ các tập tin trong bộ nhớ ngoài được mã hóa",
    "Enable recovery key": "Kích hoạt chìa khóa khôi phục",
    "Disable recovery key": "Tắt chìa khóa khôi phục",
    "The recovery key is an extra encryption key that is used to encrypt files. It allows recovery of a user's files if the user forgets his or her password.": "Chìa khóa khôi phục là chìa khóa mã hóa thêm vào để mã hóa các tập tin. Nó cho phép khôi phục các tập tin của người dùng nếu người dùng quên mật khẩu của mình.",
    "Recovery key password": "Chìa khóa mật khẩu khôi phục",
    "Repeat recovery key password": "Lặp lại chìa khóa mật khẩu khôi phục",
    "Change recovery key password:": "Thay đổi chìa khóa mật khẩu khôi phục:",
    "Old recovery key password": "Chìa khóa mật khẩu khôi phục cũ",
    "New recovery key password": "Chìa khóa mật khẩu khôi phục mới",
    "Repeat new recovery key password": "Lặp lại chìa khóa mật khẩu khôi phục mới",
    "Change Password": "Thay đổi mật khẩu",
    "ownCloud basic encryption module": "Môđun mã hóa cơ bản ownCloud",
    "Your private key password no longer matches your log-in password.": "Chìa khóa mật khẩu riêng của bạn không còn phù hợp với mật khẩu đăng nhập của bạn.",
    "Set your old private key password to your current log-in password:": "Thiết lập chìa khóa mật khẩu riêng cũ cho mật khẩu đăng nhập hiện tại của bạn:",
    "If you don't remember your old password you can ask your administrator to recover your files.": "Nếu bạn không nhớ mật khẩu cũ bạn có thể hỏi quản trị viên của bạn để khôi phục các tập tin của mình.",
    "Old log-in password": "Mật khẩu đăng nhập cũ",
    "Current log-in password": "Mật khẩu đăng nhập hiện tại",
    "Update Private Key Password": "Cập nhật chìa khóa mật khẩu riêng",
    "Enable password recovery:": "Kích hoạt mật khẩu khôi phục:",
    "Enabling this option will allow you to reobtain access to your encrypted files in case of password loss": "Kích hoạt tùy chọn này sẽ cho phép lấy lại quyền truy cập cho các tập tin được mã hóa trong trường hợp mất mật khẩu",
    "Enabled": "Đã kích hoạt"
},"nplurals=1; plural=0;");
