OC.L10N.register("gallery",{
    "Gallery": "Bộ sưu tập",
    "There was a problem reading files from this album": "Xảy ra vấn đề khi đọc tập tin từ album này",
    "Aborting preview. Could not find the file": "Hủy bỏ xem trước. Không thể tìm thấy tập tin",
    "Could not move \"{file}\", target exists": "Không thể di chuyển \"{file}\", tập tin đích đã tồn tại",
    "Could not move \"{file}\"": "Không thể di chuyển \"{file}\"",
    "No ownCloud installation (7 or higher) found at {remote}": "Không tìm thấy cài đặt ownCloud (7 hoặc cao hơn) tại {remote}",
    "Invalid ownCloud url": "ownCloud url không hợp lệ",
    "Gallery view": "Giao diện bộ sưu tập",
    "Could not load the description": "Không thể tải mô tả",
    "Could not load the description:": "Không thể tải mô tả:",
    "Copyright": "Bản quyền",
    "Could not load the copyright notice:": "Không thể tải thông báo bản quyền:",
    "Copyright notice": "Thông báo bản quyền",
    "Link to copyright document": "Liên kết đến tài liệu bản quyền",
    "This application may not work properly on your browser.": "Ứng dụng này có thể không làm việc chính xác trên trình duyệt của bạn.",
    "For an improved experience, please install one of the following alternatives": "Theo kinh nghiệm, vui lòng tải một trong số lựa chọn thay thế sau",
    "Your browser is not supported!": "Trình duyệt của bạn không được hỗ trợ!",
    "please install one of the following alternatives": "vui lòng tải một trong số lựa chọn thay thế sau",
    "Album cannot be shown": "Không thể hiển thị album",
    "No media files found": "Không tìm thấy tập tin media",
    "Upload pictures in the files app to display them here": "Tải hình lên trong tập tin ứng dụng để hiển thị chúng ở đây",
    "Upload new files via drag and drop or by using the [+] button above": "Tải tập tin mới lên thông qua kéo và thả hoặc sử dụng nút (+) bên trên",
    "Configuration error": "Lỗi cấu hình",
    "New": "Mới",
    "Error loading slideshow template": "Lỗi tải mẫu slideshow",
    "<strong>Error!<\/strong> Could not generate a preview of this file.<br>Please go to the next slide while we remove this image from the slideshow": "<strong>Lỗi!<\/strong> Không thể tạo bản xem trước của tập tin này.<br>Vui lòng chuyển sang slide kế tiếp khi chúng tôi bỏ hình này khỏi slideshow",
    "Next": "Sau",
    "Play": "Chạy",
    "Pause": "Tạm dừng",
    "Previous": "Trước",
    "Close": "Đóng",
    "Download": "Tải xuống",
    "Toggle background": "Chuyển đổi nền",
    "\"{name}\" is an invalid file name.": "\"{name}\" là một tên tập tin không hợp lệ.",
    "File name cannot be empty.": "Tên tập tin không thể bỏ trống.",
    "Upload": "Tải lên",
    "Error": "Lỗi",
    "Error while sharing": "Lỗi khi chia sẻ",
    "Error while unsharing": "Lỗi khi bỏ chia sẻ",
    "Error while changing permissions": "Lỗi khi thay đổi điều khoản",
    "Shared with you and the group {group} by {owner}": "Đã chia sẻ với bạn và nhóm {group} bởi {owner}",
    "Shared with you by {owner}": "Đã chia sẻ với bạn bởi {owner}",
    "Share with users or groups …": "Chia sẻ với người dùng hoặc nhóm…",
    "Share with users, groups or remote users …": "Chia sẻ với người dùng, nhóm hoặc người dùng từ xa…",
    "Share": "Chia sẻ",
    "Share with people on other ownClouds using the syntax username@example.com\/owncloud": "Chia sẻ với mọi người trên ownCloud khác sử dụng cú pháp username@example.com\/owncloud",
    "Share link": "Chia sẻ liên kết",
    "The public link will expire no later than {days} days after it is created": "Liên kết công khai sẽ hết hạn {days} ngày sau khi được tạo",
    "Link": "Liên kết",
    "Password protect": "Bảo vệ mật khẩu",
    "Password": "Mật khẩu",
    "Choose a password for the public link": "Chọn một mật khẩu cho liên kết công khai",
    "Allow editing": "Cho phép chỉnh sửa",
    "Email link to person": "Email liên kết đền người",
    "Send": "Gửi",
    "Set expiration date": "Thiết lập ngày hết hạn",
    "Expiration": "Hết hạn",
    "Expiration date": "Ngày hết hạn",
    "An error occured. Please try again": "Xảy ra lỗi. Vui lòng thử lại",
    "Adding user...": "Thêm người dùng…",
    "group": "nhóm",
    "remote": "từ xa",
    "Resharing is not allowed": "Không cho phép chia sẻ",
    "Error while retrieving shares": "Lỗi khi truy xuất chia sẻ",
    "Unshare": "Bỏ chia sẻ",
    "notify by email": "thông báo qua email",
    "can share": "có thể chia sẻ",
    "can edit": "có thể chỉnh sửa",
    "access control": "kiểm soát truy cập",
    "create": "tạo",
    "change": "thay đổi",
    "delete": "xóa",
    "Password protected": "Mật khẩu đã được bảo vệ",
    "Error unsetting expiration date": "Lỗi khi bỏ thiết lập ngày hết hạn",
    "Error setting expiration date": "Lỗi khi thiết lập ngày hết hạn",
    "Sending ...": "Đang gửi",
    "Email sent": "Đã gửi email",
    "Warning": "Cảnh báo",
    "This share is password-protected": "Chia sẻ này được bảo vệ mật khẩu",
    "The password is wrong. Try again.": "Mật khẩu sai. Hãy thử lại.",
    "Sort by date": "Phân loại theo ngày",
    "Sort by name": "Phân loại theo tên",
    "Cancel upload": "Hủy bỏ tải lên",
    "Album information": "Thông tin album",
    "File list": "Danh sách tập tin",
    "Sorry, this file could not be found.": "Xin lỗi, không thể tìm thấy tập tin.",
    "Reasons might be:": "Nguyên nhân có thể là:",
    "the wrong file ID was provided": "Cung cấp sai ID tập tin",
    "the file was removed": "tập tin đã bị loại bỏ",
    "the file is corrupt": "tập tin bị hỏng",
    "the encryption key is missing": "chìa khóa mã hóa bị thiếu",
    "Here is the error message returned by the server:": "Đây là tin nhắn lỗi do máy chủ gửi trả:",
    "For more information, please contact your friendly ownCloud administrator.": "Để biết thêm thông tin, vui lòng liên hệ quản trị viên ownCloud gần gũi với bạn.",
    "Sorry, but the server could not fulfill your request.": "Xin lỗi, nhưng máy chủ không thể đáp ứng yêu cầu của bạn.",
    "Possible reasons for the problem:": "Nguyên nhân cho vấn đề này có thể là:",
    "a conflicting app was installed": "một ứng dụng xung đột đã được cài đặt",
    "a required component is missing or was disconnected": "một thành tố cần thiết bị thiếu hoặc bị mất kết nối",
    "the filesystem is not readable": "hệ thống tập tin không thể đọc được",
    "Sorry, this link doesn't seem to work anymore.": "Xin lỗi, liên kết này dường như không hoạt động nữa.",
    "the item was removed": "danh mục đã bị loại bỏ",
    "the link has expired": "liên kết đã hết hạn",
    "sharing is disabled": "việc chia sẻ bị vô hiệu",
    "For more information, please ask the person who has sent you this link.": "Để biết thêm thông tin, vui lòng hỏi người đã gửi liên kết này cho bạn.",
    "Add to your ownCloud": "Thêm vào ownCloud của bạn"
},"nplurals=1; plural=0;");