OC.L10N.register("core",{
    "Please select a file.": "Hãy chọn một tập tin",
    "File is too big": "Tập tin quá lớn",
    "Invalid file provided": "Tập tin không hợp lệ",
    "No image or file provided": "Chưa cung cấp hình hoặc tập tin",
    "Unknown filetype": "Loại tập tin không xác định",
    "Invalid image": "Hình không hợp lệ",
    "An error occurred. Please contact your admin.": "Xảy ra lỗi. Vui lòng liên hệ quản trị viên của bạn.",
    "No temporary profile picture available, try again": "Không có sẵn hình hồ sơ tạm thời, hãy thử lại",
    "No crop data provided": "Chưa cung cấp dữ liệu cắt",
    "No valid crop data provided": "Chưa cung cấp dữ liệu cắt hợp lệ",
    "Crop is not square": "Cắt không vuông",
    "Couldn't reset password because the token is invalid": "Không thể thiết lập lại mật khẩu vì mã thông báo không hợp lệ",
    "Couldn't reset password because the token is expired": "Không thể thiết lập lại mật khẩu vì mã thông báo đã hết ạn",
    "Couldn't send reset email. Please make sure your username is correct.": "Không thể gửi email thiết lập lại. Hãy đảm bảo tên người dùng của bạn là chính xác.",
    "Could not send reset email because there is no email address for this username. Please contact your administrator.": "Không thể gửi email thiết lập lại vì không có địa chỉ email với tên người dùng này. Vui lòng liên hệ quản trị viên của bạn.",
    "%s password reset": "%s thiết lập lại mật khẩu",
    "Couldn't send reset email. Please contact your administrator.": "Không thể gửi email thiết lập lại. Vui lòng liên hệ quản trị viên của bạn.",
    "Error loading tags": "Lỗi tải từ khóa",
    "Tag already exists": "Từ khóa đã tồn tại",
    "Error deleting tag(s)": "Lỗi xóa từ khóa",
    "Error tagging": "Lỗi gắn từ khóa",
    "Error untagging": "Lỗi bỏ gắn từ khóa",
    "Error favoriting": "Lỗi chọn yêu thích ",
    "Error unfavoriting": "Lỗi bỏ chọn yêu thích ",
    "Couldn't send mail to following users: %s": "Không thể gửi thư đến người dùng sau: %s",
    "Preparing update": "Chuẩn bị cập nhật",
    "[%d \/ %d]: %s": "[%d \/ %d]: %s",
    "Repair warning:": "Sửa cảnh báo:",
    "Repair error:": "Sửa lỗi:",
    "Please use the command line updater because automatic updating is disabled in the config.php.": "Xin vui lòng sử dụng dòng lệnh trình cập nhật vì cập nhật tự động bị vô hiệu trong config.php.",
    "[%d \/ %d]: Checking table %s": "[%d \/ %d]: Bảng kiểm tra %s",
    "Turned on maintenance mode": "Bật chế độ bảo trì",
    "Turned off maintenance mode": "Tắt chế độ bảo trì",
    "Maintenance mode is kept active": "Chế độ bảo trì đang hoạt động",
    "Updating database schema": "Đang cập nhật  giản đồ cơ sở dữ liệu",
    "Updated database": "Cơ sở dữ liệu đã được cập nhật",
    "Checking whether the database schema can be updated (this can take a long time depending on the database size)": "Kiểm tra nếu giản đồ cơ sở dữ liệu có thể được cập nhật (quá trình này có thể sẽ tốn thời gian dựa vào kích cỡ cơ sở dữ liệu)",
    "Checked database schema update": "Đã kiểm tra cập nhật  giản đồ cơ sở dữ liệu",
    "Checking updates of apps": "Đang kiểm tra cập nhật ứng dụng",
    "Checking whether the database schema for %s can be updated (this can take a long time depending on the database size)": "Đang kiểm tra nếu giản đồ cơ sở dữ liệu cho %s có thể cập nhật (quá trình này có thể sẽ tốn thời gian dựa vào kích cỡ cơ sở dữ liệu)",
    "Checked database schema update for apps": "Đã kiểm tra cập nhật  giản đồ cơ sở dữ liệu cho các ứng dụng",
    "Updated \"%s\" to %s": "Đã cập nhật \"%s\" thành %s",
    "Set log level to debug": "Thiết lập chế độ đăng nhập thành sửa lỗi",
    "Reset log level": "Thiết lập lại chế độ đăng nhập",
    "Starting code integrity check": "Kiểm tra tính nhất quán của mã bắt đầu",
    "Finished code integrity check": "Kiểm tra tính nhất quán của mã kết thúc",
    "%s (3rdparty)": "%s (bên thứ 3)",
    "%s (incompatible)": "%s (không tương thích)",
    "Following apps have been disabled: %s": "Các ứng dụng sau đã bị vô hiệu: %s",
    "Already up to date": "Đã là phiên bản mới nhất",
    "Sunday": "Chủ nhật",
    "Monday": "Thứ hai",
    "Tuesday": "Thứ ba",
    "Wednesday": "Thứ tư",
    "Thursday": "Thứ năm",
    "Friday": "Thứ sáu",
    "Saturday": "Thứ bảy",
    "Sun.": "Chủ nhật",
    "Mon.": "Thứ hai",
    "Tue.": "Thứ ba",
    "Wed.": "Thứ tư",
    "Thu.": "Thứ năm",
    "Fri.": "Thứ sáu",
    "Sat.": "Thứ bảy",
    "Su": "Chủ nhật",
    "Mo": "Thứ hai",
    "Tu": "Thứ ba",
    "We": "Thứ tư",
    "Th": "Thứ năm",
    "Fr": "Thứ sáu",
    "Sa": "Thứ bảy",
    "January": "Tháng 1",
    "February": "Tháng 2",
    "March": "Tháng 3",
    "April": "Tháng 4",
    "May": "Tháng 5",
    "June": "Tháng 6",
    "July": "Tháng 7",
    "August": "Tháng 8",
    "September": "Tháng 9",
    "October": "Tháng 10",
    "November": "Tháng 11",
    "December": "Tháng 12",
    "Jan.": "Tháng 1",
    "Feb.": "Tháng 2",
    "Mar.": "Tháng 3",
    "Apr.": "Tháng 4",
    "May.": "Tháng 5",
    "Jun.": "Tháng 6",
    "Jul.": "Tháng 7",
    "Aug.": "Tháng 8",
    "Sep.": "Tháng 9",
    "Oct.": "Tháng 10",
    "Nov.": "Tháng 11",
    "Dec.": "Tháng 12",
    "<a href=\"{docUrl}\">There were problems with the code integrity check. More information…<\/a>": "<a href=\"{docUrl}\">Đã có vấn đề với việc kiểm tra tính nhất quán của các mã. Thông tin thêm...<\/a>",
    "Settings": "Thiết lập",
    "Problem loading page, reloading in 5 seconds": "Gặp vấn đề tải trang, tải lại sau 5 giây",
    "Saving...": "Đang lưu…",
    "Dismiss": "Bỏ qua",
    "seconds ago": "giây trước",
    "The link to reset your password has been sent to your email. If you do not receive it within a reasonable amount of time, check your spam\/junk folders.<br>If it is not there ask your local administrator.": true,
    "Your files are encrypted. If you haven't enabled the recovery key, there will be no way to get your data back after your password is reset.<br \/>If you are not sure what to do, please contact your administrator before you continue. <br \/>Do you really want to continue?": true,
    "I know what I'm doing": "Tôi biết tôi đang làm gì",
    "Password can not be changed. Please contact your administrator.": "Không thể thay đổi mật khẩu.. Vui lòng liên hệ quản trị viên của bạn.",
    "No": "Không   ",
    "Yes": "Có",
    "Choose": "Lựa chọn",
    "Error loading file picker template: {error}": "Lỗi tải mẫu chọn tập tin: {error}",
    "Ok": "Ok",
    "Error loading message template: {error}": "Lỗi tải mẫu tin nhắn: {error}",
    "read-only": "chỉ cho đọc",
    "_{count} file conflict_::_{count} file conflicts_": "_{count} xung đột tập tin_::_{count} xung đột tập tin_",
    "One file conflict": "Một xung đột tập tin",
    "New Files": "Tập tin mới",
    "Already existing files": "Tâp tin đã tồn tại",
    "Which files do you want to keep?": "Bạn muốn giữ tập tin nào?",
    "If you select both versions, the copied file will have a number added to its name.": "Nếu bạn chọn cả hai phiên bản, tập tin được sao sẽ có con số đi kèm với tên của nó.",
    "Cancel": "Hủy bỏ",
    "Continue": "Tiếp tục",
    "(all selected)": "(chọn tất cả)",
    "({count} selected)": "({count} được chọn)",
    "Error loading file exists template": "Lỗi tải mẫu tập tin đã có",
    "Very weak password": "Mật khẩu rất yếu",
    "Weak password": "Mật khẩu yếu",
    "So-so password": "Mật khẩu bình thường",
    "Good password": "Mật khẩu tốt",
    "Strong password": "Mật khẩu mạnh",
    "Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.": "Máy chủ trang web của bạn không được thiết lập cho phép đồng bộ hóa tập tin vì giao diện WebDAV sẽ bị hỏng.",
    "Your web server is not set up properly to resolve \"{url}\". Further information can be found in our <a target=\"_blank\" rel=\"noreferrer\" href=\"{docLink}\">documentation<\/a>.": true,
    "This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.": true,
    "No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our <a target=\"_blank\" rel=\"noreferrer\" href=\"{docLink}\">documentation<\/a>.": true,
    "\/dev\/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our <a target=\"_blank\" rel=\"noreferrer\" href=\"{docLink}\">documentation<\/a>.": true,
    "You are currently running PHP {version}. We encourage you to upgrade your PHP version to take advantage of <a target=\"_blank\" rel=\"noreferrer\" href=\"{phpLink}\">performance and security updates provided by the PHP Group<\/a> as soon as your distribution supports it.": true,
    "The reverse proxy headers configuration is incorrect, or you are accessing ownCloud from a trusted proxy. If you are not accessing ownCloud from a trusted proxy, this is a security issue and can allow an attacker to spoof their IP address as visible to ownCloud. Further information can be found in our <a target=\"_blank\" rel=\"noreferrer\" href=\"{docLink}\">documentation<\/a>.": true,
    "Memcached is configured as distributed cache, but the wrong PHP module \"memcache\" is installed. \\OC\\Memcache\\Memcached only supports \"memcached\" and not \"memcache\". See the <a target=\"_blank\" rel=\"noreferrer\" href=\"{wikiLink}\">memcached wiki about both modules<\/a>.": true,
    "Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our <a target=\"_blank\" rel=\"noreferrer\" href=\"{docLink}\">documentation<\/a>. (<a href=\"{codeIntegrityDownloadEndpoint}\">List of invalid files…<\/a> \/ <a href=\"{rescanEndpoint}\">Rescan…<\/a>)": true,
    "Error occurred while checking server setup": true,
    "Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root.": true,
    "The \"{header}\" HTTP header is not configured to equal to \"{expected}\". This is a potential security or privacy risk and we recommend adjusting this setting.": true,
    "The \"Strict-Transport-Security\" HTTP header is not configured to at least \"{seconds}\" seconds. For enhanced security we recommend enabling HSTS as described in our <a href=\"{docUrl}\" rel=\"noreferrer\">security tips<\/a>.": true,
    "You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our <a href=\"{docUrl}\">security tips<\/a>.": true,
    "Shared": "Đã chia sẻ",
    "Shared with {recipients}": "Đã chia sẻ với {recipients}",
    "Error": "Lỗi",
    "Error while sharing": "Lỗi khhi chia sẻ",
    "Error while unsharing": "Lỗi khi bỏ chia sẻ",
    "Error setting expiration date": "Lỗi khi thiết lập ngày hết hạn",
    "The public link will expire no later than {days} days after it is created": "Liên kết công khai sẽ hết hạn sau ngày {days} sau khi được tạo",
    "Set expiration date": "Thiết lập ngày hết hạn",
    "Expiration": "Hết hạn",
    "Expiration date": "Ngày hết hạn",
    "Choose a password for the public link": "Chọn mật khẩu cho liên kết công khai",
    "Resharing is not allowed": "Không cho phép chia sẻ lại",
    "Share link": "Chia sẻ liên kết",
    "Link": "Liên kết ",
    "Password protect": "Bảo vệ mật khẩu",
    "Password": "Mật khẩu",
    "Allow editing": "Cho phép chỉnh sửa",
    "Email link to person": "Email liên kết đến",
    "Send": "Gửi",
    "Sending ...": "Đang gửi…",
    "Email sent": "Email đã gửi",
    "Send link via email": "Gửi liên kết thông qua email",
    "Shared with you and the group {group} by {owner}": "Đã được {owner} chia sẻ với bạn và nhóm {group} ",
    "Shared with you by {owner}": "Đã được {owner} chia sẻ với bạn",
    "group": "nhóm",
    "remote": "từ xa",
    "notify by email": "thông báo qua email",
    "Unshare": "Bỏ chia sẻ",
    "can share": "có thể chia sẻ",
    "can edit": "có thể chỉnh sửa",
    "create": "tạo",
    "change": "thay đổi",
    "delete": "xóa",
    "access control": "kiểm soát truy cập",
    "Could not unshare": "Không thể bỏ chia sẻ",
    "Share details could not be loaded for this item.": "Chi tiết chia sẻ không thể tải lên cho danh mục này.",
    "No users or groups found for {search}": "Không tìm thấy người dùng hoặc nhóm với {search}",
    "No users found for {search}": "Không tìm thấy người dùng với {search}",
    "An error occurred. Please try again": "Xảy ra lỗi. Vui lòng thử lại",
    "{sharee} (group)": "{sharee} (nhóm)",
    "{sharee} (at {server})": "{sharee} (tại {server})",
    "{sharee} (remote)": "{sharee} từ xa",
    "Share": "Chia sẻ  ",
    "Share with people on other ownClouds using the syntax username@example.com\/owncloud": "Chia sẻ với mọi người trên ownClouds dùng cú pháp username@example.com\/owncloud",
    "Share with users…": "Chia sẻ với người dùng…",
    "Share with users, groups or remote users…": "Chia sẻ với người dùng, nhóm hoặc người dùng từ xa…",
    "Share with users or groups…": "Chia sẻ với người dùng hoặc người dùng từ xa…",
    "Share with users or remote users…": "Chia sẻ với người dùng hoặc nhóm…",
    "Error removing share": "Lỗi loại bỏ chia sẻ",
    "Warning": "Cảnh báo",
    "Error while sending notification": "Lỗi khi gửi thông báo",
    "Non-existing tag #{tag}": "Từ khóa không tồn tại #{tag}",
    "restricted": "bị hạn chế",
    "invisible": "không xem được",
    "({scope})": "({scope})",
    "Delete": "Xóa",
    "Rename": "Đặt lại tên",
    "Collaborative tags": "Từ khóa kết hợp",
    "The object type is not specified.": "Loại đối tượng chưa được xác định.",
    "Enter new": "Nhập mới",
    "Add": "Thêm",
    "Edit tags": "Chỉnh sửa từ khóa",
    "Error loading dialog template: {error}": "Lỗi tải mẫu hội thoại: {error}",
    "No tags selected for deletion.": "Không có từ khóa được chọn để xóa.",
    "unknown text": "văn bản không xác định",
    "Hello world!": "Xin chào tất cả!",
    "sunny": "nắng",
    "Hello {name}, the weather is {weather}": "Xin chào {name}, thời tiết {weather}",
    "Hello {name}": "Xin chào {name}",
    "new": "mới",
    "_download %n file_::_download %n files_": "_tải xuống tập tin %n file_::_tải xuống các tập tin %n_",
    "The upgrade is in progress, leaving this page might interrupt the process in some environments.": "Đang tiến hành cập nhật, rời khỏi trang sẽ gây gián đoạn việc xử lý trong một số môi trường.",
    "Updating to {version}": "Đang cập nhật lên {version}",
    "An error occurred.": "Lỗi xảy ra.",
    "Please reload the page.": "Vui lòng tải lại trang.",
    "The update was unsuccessful. For more information <a href=\"{url}\">check our forum post<\/a> covering this issue.": "Cập nhật không thành công. Để biết thêm thông tin <a href=\"{url}\"> kiểm tra bài đăng diễn đàn của chúng tôi <\/a> liên quan đến vấn đề này.",
    "The update was unsuccessful. Please report this issue to the <a href=\"https:\/\/github.com\/owncloud\/core\/issues\" target=\"_blank\">ownCloud community<\/a>.": true,
    "The update was successful. There were warnings.": "Cập nhật không thành công. Đã có cảnh báo.",
    "The update was successful. Redirecting you to ownCloud now.": "Cập nhật không thành công. Đang chuyển hướng bạn về ownCloud.",
    "Searching other places": "Đang tìm nơi khác",
    "No search results in other folders": "Không có kết quả tìm kiếm trong thư mục khác",
    "_{count} search result in another folder_::_{count} search results in other folders_": "_{count} kết quả tìm kiếm trong thư mục khác_::_{count} các kết quả tìm kiếm trong các thư mục khác_",
    "Personal": "Cá nhân",
    "Users": "Người dùng",
    "Apps": "Ứng dụng",
    "Admin": "Quản trị viên",
    "Help": "Hỗ trợ",
    "Access forbidden": "Truy cập bị cấm",
    "File not found": "Không tìm thấy tập tin",
    "The specified document has not been found on the server.": "Không tìm thấy tài liệu được xác định trong máy chủ này.",
    "You can click here to return to %s.": "Bạn có thể nhấp vào đây để quay lại %s.",
    "Hey there,\n\njust letting you know that %s shared %s with you.\nView it: %s": "Xin chào, chúng tôi chỉ muốn cho bạn biết rằng %s đã chia sẻ %s với bạn. Xem: %s",
    "The share will expire on %s.": "Chia sẻ này sẽ hết hạn vào %s.",
    "Cheers!": "Chúc mừng!",
    "Internal Server Error": "Lỗi máy chủ cục bộ",
    "The server encountered an internal error and was unable to complete your request.": "Máy chủ gặp lỗi cục bộ và không thể hoàn thành yêu cầu của bạn.",
    "Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.": true,
    "More details can be found in the server log.": "Có thể tìm thấy thêm thông tin chi tiết trong phần giải thích máy chủ.",
    "Technical details": "Chi tiết kỹ thuật",
    "Remote Address: %s": "Địa chỉ từ xa: %s",
    "Request ID: %s": "ID yêu cầu: %s",
    "Type: %s": "Loại: %s",
    "Code: %s": "Mã: %s",
    "Message: %s": "Tin nhắn: %s",
    "File: %s": "Tập tin: %s",
    "Line: %s": "Danh mục: %s",
    "Trace": "Theo dõi",
    "Security warning": "Cảnh báo bảo mật",
    "Your data directory and files are probably accessible from the internet because the .htaccess file does not work.": "Thư mục và tập tin dữ liệu của bạn có thể bị truy câp từ internet vì tập tin .htaccess không hoạt động.",
    "For information how to properly configure your server, please see the <a href=\"%s\" target=\"_blank\" rel=\"noreferrer\">documentation<\/a>.": "Thông tin về cách cấu hình chính xác máy chủ của bạn, vui lòng xem tài liệu <a href=\"%s\" target=\"_blank\" rel=\"noreferrer\"><\/a>.",
    "Create an <strong>admin account<\/strong>": "Tạo một <strong>tài khoản quản trị<\/strong>",
    "Username": "Tên người dùng",
    "Storage & database": "Lưu trữ & cơ sở dữ liệu",
    "Data folder": "Thư mục dữ liệu",
    "Configure the database": "Cấu hình cơ sở dữ liệu",
    "Only %s is available.": "Chỉ có sẵn %s.",
    "Install and activate additional PHP modules to choose other database types.": "Cài đặt và kích hoạt môđun PHP bổ sung để chọn loại cơ sở dữ liệu khác.",
    "For more details check out the documentation.": "Để biết thêm thông tin hãy kiểm tra tài liệu này",
    "Database user": "Người dùng cơ sở dữ liệu",
    "Database password": "Mật khẩu cơ sở dữ liệu",
    "Database name": "Tên cơ sở dữ liệu",
    "Database tablespace": "Bảng nhóm cơ sở dữ liệu",
    "Database host": "Máy chủ cơ sở dữ liệu",
    "Performance warning": "Cảnh báo hoạt động",
    "SQLite will be used as database.": "SQLite sẽ được dùng là cơ sở dữ liệu",
    "For larger installations we recommend to choose a different database backend.": "Cho việc cài đặt dung lượng lớn hơn chúng tôi khuyên bạn nên chọn một phụ trợ cơ sở dữ liệu khác.",
    "Especially when using the desktop client for file syncing the use of SQLite is discouraged.": "Đặc biệt là khi sử dụng màn hình khách để đồng bộ hóa tập tin, SQLite được khuyến khích sử dụng",
    "Finish setup": "Kết thúc thiết lập",
    "Finishing …": "Đang kết thúc...",
    "Need help?": "Cần hỗ trợ?",
    "See the documentation": "Xem tài liệu",
    "Hey there,<br><br>just letting you know that %s shared <strong>%s<\/strong> with you.<br><a href=\"%s\">View it!<\/a><br><br>": "Xin chào, <br><br>chúng tôi chỉ muốn cho bạn biết rằng %s đã chia sẻ<strong>%s<\/strong> với bạn. <br><a href=\"%s\">Hãy xem!<\/a><br><br> ",
    "This application requires JavaScript for correct operation. Please {linkstart}enable JavaScript{linkend} and reload the page.": "Ứng dụng này yêu cầu JavaScript để hoạt động chính xác. Vui lòng, kích hoạt {linkstart} JavaScript {linkend} và tải lại trang.",
    "Log out": "Đăng xuất",
    "Search": "Tìm kiếm",
    "Server side authentication failed!": "Xác thực phía máy chủ thất bại!",
    "Please contact your administrator.": "Vui lòng liên hệ quản trị viên của bạn.",
    "An internal error occurred.": "Xảy ra lỗi cục bộ.",
    "Please try again or contact your administrator.": "Vui lòng thử lại hoặc liên hệ quản trị viên của bạn.",
    "Username or email": "Tên người dùng hoặc email",
    "Log in": "Đăng nhập",
    "Wrong password. Reset it?": "Mật khẩu sai. Thiết lập lại?",
    "Wrong password.": "Mật khẩu sai. ",
    "Stay logged in": "Duy trì đăng nhập",
    "Alternative Logins": "Thông tin đăng nhập khác",
    "Use the following link to reset your password: {link}": "Sử dụng liên kết sau để thiết lập lại mật khẩu của bạn: {link}",
    "New password": "Mật khẩu mới",
    "New Password": "Mật khẩu mới",
    "Reset password": "Thiết lập lại mật khẩu",
    "This ownCloud instance is currently in single user mode.": "Trường hợp ownCloud này hiện đang ở chế độ một người dùng.",
    "This means only administrators can use the instance.": "Điều này có nghĩa là chỉ quản trị viên có thể sử dụng trường hợp này.",
    "Contact your system administrator if this message persists or appeared unexpectedly.": "Liên hệ quản trị viên hệ thống của bạn nếu tin nhắn này vẫn còn tồn tại hoặc xuất hiện bất ngờ.",
    "Thank you for your patience.": "Cảm ơn vì đã kiên nhẫn.",
    "Two-step verification": "Xác nhận hai bước",
    "Enhanced security has been enabled for your account. Please authenticate using a second factor.": "Bảo mật tăng cường đã được kích hoạt cho tài khoản của bạn. Vui lòng xác thực dùng yếu tố thứ hai.",
    "Cancel login": "Hủy đăng nhập",
    "Please authenticate using the selected factor.": "Vui lòng xác thực sử dụng yếu tố được chọn.",
    "An error occured while verifying the token": "Lỗi xảy ra khi xác nhận mã thông báo",
    "You are accessing the server from an untrusted domain.": "Bạn đang truy cập vào máy chủ từ tên miền không đáng tin cậy.",
    "Please contact your administrator. If you are an administrator of this instance, configure the \"trusted_domains\" setting in config\/config.php. An example configuration is provided in config\/config.sample.php.": true,
    "Depending on your configuration, as an administrator you might also be able to use the button below to trust this domain.": "Dựa trên cấu hình của bạn, là quản trị viên bạn cũng có thể sử dụng nút dưới đây để tin tưởng tên miền này.",
    "Add \"%s\" as trusted domain": "Thêm \"%s\" là tên miền đáng tin cậy",
    "App update required": "Yêu cầu cập nhật ứng dụng ",
    "%s will be updated to version %s": "%s sẽ được cập nhật lên phiên bản %s",
    "These apps will be updated:": "Các ứng dụng này sữ được cập nhật:",
    "These incompatible apps will be disabled:": "Các ứng dụng không tương thích này sẽ bị dừng:",
    "The theme %s has been disabled.": "Chủ đề %s đã bị tắt.",
    "Please make sure that the database, the config folder and the data folder have been backed up before proceeding.": "Vui lòng đảm bảo rằng cơ sở dữ liệu, thư mục cấu hình và thư mục dữ liệu đã được sao lưu trước khi tiến hành.",
    "Start update": "Bắt đầu cập nhật",
    "To avoid timeouts with larger installations, you can instead run the following command from your installation directory:": "Để tránh tốn thêm thời gian với cài đặt lớn hơn, bạn có thể chạy lệnh dưới đây từ thư mục cài đặt của bạn:",
    "Detailed logs": "Giải thích chi tiết",
    "Update needed": "Cần cập nhật",
    "Please use the command line updater because you have a big instance.": "Vui lòng sử dụng trình cập nhật dòng lệnh vì bạn có trường hợp khó.",
    "For help, see the  <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">documentation<\/a>.": "Nếu cần hỗ trợ, xem tài liệu <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\"><\/a>.",
    "This %s instance is currently in maintenance mode, which may take a while.": "Trường hợp %s này hiện đang ở chế độ bảo trì, nên sẽ tốn chút thời gian."
},"nplurals=1; plural=0;");