OC.L10N.register("files_sharing",{
    "Server to server sharing is not enabled on this server": "Chia sẻ từ máy chủ sang máy chủ không được phép trên máy chủ này",
    "The mountpoint name contains invalid characters.": "Tên điểm gắn kết chứa ký tự không hợp lệ.",
    "Not allowed to create a federated share with the same user server": "Không cho phép tạo chia sẻ tổ hợp với cùng máy chủ người dùng",
    "Invalid or untrusted SSL certificate": "Chứng chỉ SSL không hợp lệ hoặc không đáng tin cậy",
    "Could not authenticate to remote share, password might be wrong": "Không thể xác thực chia sẻ từ xa, có thể mật khẩu sai",
    "Storage not valid": "Bộ nhớ không hợp lệ",
    "Couldn't add remote share": "Không thể thêm chia sẻ từ xa",
    "Shared with you": "Được chia sẻ với bạn",
    "Shared with others": "Được chia sẻ với người khác",
    "Shared by link": "Được chia sẻ theo liên kết",
    "Nothing shared with you yet": "Chưa có chia sẻ với bạn",
    "Files and folders others share with you will show up here": "Tập tin hoặc thư mục người khác chia sẻ với bạn sẽ được hiển thị ở đây",
    "Nothing shared yet": "Chưa có chia sẻ",
    "Files and folders you share will show up here": "Tập tin hoặc thư mục bạn chia sẻ sẽ được hiển thị ở đây",
    "No shared links": "Không có liên kết chia sẻ",
    "Files and folders you share by link will show up here": "Tập tin hoặc thư mục bạn chia sẻ theo liên kết sẽ được hiển thị ở đây",
    "Do you want to add the remote share {name} from {owner}@{remote}?": "Bạn có muốn thêm chia sẻ từ xa {name} từ {owner}@{remote}?",
    "Remote share": "Chia sẻ từ xa",
    "Remote share password": "Mật khẩu chia sẻ từ xa",
    "Cancel": "Hủy bỏ",
    "Add remote share": "Thêm chia sẻ từ xa",
    "You can upload into this folder": "Bạn có thể tải lên vào thư mục này",
    "No ownCloud installation (7 or higher) found at {remote}": "Không tìm thấy cài đặt ownCloud (7 hoặc cao hơn) tại {remote}",
    "Invalid ownCloud url": "url ownCloud không hợp lệ",
    "Shared by": "Chia sẻ bởi",
    "Sharing": "Đang chia sẻ",
    "Share API is disabled": "API chia sẻ bị vô hiệu",
    "Wrong share ID, share doesn't exist": "ID chia sẻ sai, chia sẻ không tồn tại",
    "Could not delete share": "Không thể xóa chia sẻ",
    "Please specify a file or folder path": "Vui lòng xác định một đường dẫn tập tin hoặc thư mục",
    "Wrong path, file\/folder doesn't exist": "Đường dẫn sai, tập tin\/thư mục không tồn tại",
    "Please specify a valid user": "Vui lòng xác định một người dùng hợp lệ",
    "Group sharing is disabled by the administrator": "Chia sẻ theo nhóm bị vô hiệu bởi quản trị viên ",
    "Please specify a valid group": "Vui lòng xác định một nhóm hợp lệ",
    "Public link sharing is disabled by the administrator": "Chia sẻ liên kết công khai bị vô hiệu bởi quản trị viên",
    "Public upload disabled by the administrator": "Tải lên công khai bị vô hiệu bởi quản trị viên",
    "Public upload is only possible for publicly shared folders": "Tải lên công khai chỉ dành cho thư mục được chia sẻ công khai",
    "Invalid date, date format must be YYYY-MM-DD": "Ngày không hợp lệ, định dạng ngày phải là YYYY-MM-DD",
    "Sharing %s failed because the back end does not allow shares from type %s": "Chia sẻ %s thất bại vì phụ trợ không cho phép chia sẻ từ loại %s",
    "Unknown share type": "Loại chia sẻ không xác định",
    "Not a directory": "Không phải là thư mục",
    "Could not lock path": "Không thể khóa đường dẫn",
    "Can't change permissions for public share links": "Không thể thay đổi điều khoản cho liên kết chia sẻ công khai",
    "Wrong or no update parameter given": "Thông số cung cấp sai hoặc chưa được cập nhật",
    "Cannot increase permissions": "Không thể tăng điều khoản",
    "A file or folder has been <strong>shared<\/strong>": "Một tập tin hoặc thư mục đã được <strong>chia sẻ<\/strong>",
    "A file or folder was shared from <strong>another server<\/strong>": "Một tập tin hoặc thư mục đã được chia sẻ từ <strong>một máy chủ khác<\/strong>",
    "A public shared file or folder was <strong>downloaded<\/strong>": "Một tập tin hoặc thư mục được chia sẻ công khai đã <strong>được tải xuống<\/strong>",
    "You received a new remote share %2$s from %1$s": "Bạn nhận được một chia sẻ từ xa mới %2$s từ %1$s",
    "You received a new remote share from %s": "Bạn nhận được một chia sẻ từ xa mới  từ %s",
    "%1$s accepted remote share %2$s": "%1$s đã chấp nhận chia sẻ từ xa %2$s",
    "%1$s declined remote share %2$s": "%1$s đã từ chối chia sẻ từ xa %2$s",
    "%1$s unshared %2$s from you": "%1$s đã bỏ chia sẻ %2$s từ bạn",
    "Public shared folder %1$s was downloaded": "Thư mục được chia sẻ công khai %1$s đã được tải xuống",
    "Public shared file %1$s was downloaded": "Tập tin được chia sẻ công khai %1$s đã được tải xuống",
    "You shared %1$s with %2$s": "Bạn đã chia sẻ %1$s với %2$s ",
    "%2$s shared %1$s with %3$s": "%2$s đã chia sẻ %1$s với %3$s ",
    "You removed the share of %2$s for %1$s": "Bạn đã bỏ chia sẻ %2$s cho %1$s",
    "%2$s removed the share of %3$s for %1$s": "%2$s đã bỏ chia sẻ %3$s cho %1$s",
    "You shared %1$s with group %2$s": "Bạn đã chia sẻ %1$s với nhóm %2$s ",
    "%2$s shared %1$s with group %3$s": "%2$s đã chia sẻ %1$s với nhóm %3$s ",
    "You removed the share of group %2$s for %1$s": "Bạn đã bỏ chia sẻ nhóm %2$s cho %1$s",
    "%2$s removed the share of group %3$s for %1$s": "%2$s đã bỏ chia sẻ nhóm %3$s cho %1$s",
    "%2$s shared %1$s via link": "%2$s đã chia sẻ %1$s thông qua liên kết",
    "You shared %1$s via link": "Bạn đã chia sẻ %1$s thông qua liên kết",
    "You removed the public link for %1$s": "Bạn đã bỏ liên kết công khai cho %1$s",
    "%2$s removed the public link for %1$s": "%2$s đã bỏ liên kết công khai cho %1$s",
    "Your public link for %1$s expired": "Liên kết công khai của bạn cho %1$s đã hết hạn",
    "The public link of %2$s for %1$s expired": "Liên kết công khai của %2$s cho %1$s đã hết hạn",
    "%2$s shared %1$s with you": "%2$s đã chia sẻ %1$s với bạn",
    "%2$s removed the share for %1$s": "%2$s đã bỏ chia sẻ cho %1$s",
    "Downloaded via public link": "Đã tải xuống thông qua liên kết công khai",
    "Shared with %2$s": "Đã chia sẻ với %2$s",
    "Shared with %3$s by %2$s": "Đã chia sẻ với %3$s bởi %2$s",
    "Removed share for %2$s": "Đã bỏ chia sẻ cho %2$s",
    "%2$s removed share for %3$s": "%2$s đã bỏ chia sẻ cho %3$s",
    "Shared with group %2$s": "Đã chia sẻ với nhóm %2$s ",
    "Shared with group %3$s by %2$s": "Đã chia sẻ với nhóm %3$s bởi %2$s",
    "Removed share of group %2$s": "Đã bỏ chia sẻ của nhóm %2$s",
    "%2$s removed share of group %3$s": "%2$s đã bỏ chia sẻ của nhóm %3$s",
    "Shared via link by %2$s": "Đã chia sẻ thông qua liên kết bởi %2$s ",
    "Shared via public link": "Đã chia sẻ thông qua liên kết công khai ",
    "Removed public link": "Đã bỏ liên kết công khai ",
    "%2$s removed public link": "%2$s đã bỏ liên kết công khai cho %1$s",
    "Public link expired": "Liên kết công khai đã hết hạn",
    "Public link of %2$s expired": "Liên kết công khai của %2$s đã hết hạn",
    "Shared by %2$s": "Đã chia sẻ bởi %2$s",
    "Shares": "Chia sẻ",
    "This share is password-protected": "Chia sẻ này được bảo vệ mật khẩu",
    "The password is wrong. Try again.": "Mật khẩu sai. Hãy thử lại.",
    "Password": "Mật khẩu",
    "No entries found in this folder": "Không tìm thấy nhập liệu nào trong thư mục này",
    "Name": "Tên",
    "Share time": "Thời gian chia sẻ",
    "Sorry, this link doesn’t seem to work anymore.": "Xin lỗi, liên kết này dường như không còn nữa.",
    "Reasons might be:": "Nguyên nhân có thể do:",
    "the item was removed": "danh mục đã bị loại bỏ",
    "the link expired": "liên kết hết hạn",
    "sharing is disabled": "việc chia sẻ bị vô hiệu",
    "For more info, please ask the person who sent this link.": "Để biết thêm thông tin, vui lòng hỏi người đã gửi liên kết này.",
    "Add to your ownCloud": "Thêm vào ownCloud của bạn",
    "Download": "Tải xuống",
    "Download %s": "Tải xuống %s"
},"nplurals=1; plural=0;");