OC.L10N.register("setting",{
    "Wrong password": "Sai mật khẩu",
    "No user supplied": "Không cung cấp người dùng nào",
    "Authentication error": "Lỗi xác thực",
    "Please provide an admin recovery password, otherwise all user data will be lost": "Vui lòng cung cấp một mật khẩu khôi phục quản trị, nếu không tất cả dữ liệu người dùng sẽ bị mất ",
    "Wrong admin recovery password. Please check the password and try again.": "Mật khẩu khôi phục quản trị sai. Vui lòng kiểm tra mật khẩu và hử lại.",
    "Backend doesn't support password change, but the user's encryption key was successfully updated.": "Phụ trợ không hỗ trợ thay đổi mật khẩu, nhưng mã khóa người dùng được cập nhật thành công.",
    "Unable to change password": "Không thể thay đổi mật khẩu",
    "Enabled": "Đã kích hoạt",
    "Not enabled": "Không đươc kích hoạt",
    "installing and updating apps via the app store or Federated Cloud Sharing": "cài đặt và cập nhật các ứng dụng thông qua app store hoặc chia sẻ đám mây ",
    "Federated Cloud Sharing": "Chia sẻ tập hợp đám mây",
    "cURL is using an outdated %s version (%s). Please update your operating system or features such as %s will not work reliably.": "cURL sử dụng phiên bản lỗi thời %s (%s). Xin vui lòng cập nhật hệ điều hành nếu không các tính năng như %s sẽ không hoạt động đúng quy trình.",
    "A problem occurred, please check your log files (Error: %s)": "Xảy ra lỗi, vui lòng kiểm tra tập tin đăng nhập của bạn (Lỗi: %s)",
    "Migration Completed": "Di chuyển hoàn tất",
    "Group already exists.": "Nhóm đã tồn tại.",
    "Unable to add group.": "Không thể thêm nhóm.",
    "Unable to delete group.": "Không thể xóa nhóm.",
    "log-level out of allowed range": "mức đăng nhập ngoài vùng cho phép",
    "Saved": "Đã lưu",
    "test email settings": "kiểm tra thiết lập email",
    "A problem occurred while sending the email. Please revise your settings. (Error: %s)": "Xảy ra lỗi khi gửi email, vui lòng kiểm tra thiết lập của bạn (Lỗi: %s)",
    "Email sent": "Email đã gửi",
    "You need to set your user email before being able to send test emails.": "Bạn cần thiết lập email người dùng trước khi có thể gửi email thử nghiệm.",
    "Invalid mail address": "Địa chỉ email không hợp lệ",
    "A user with that name already exists.": "Người dùng với tên này đã tồn tại.",
    "Unable to create user.": "Không thể tạo người dùng",
    "Your %s account was created": "Tài khoản %s của bạn đã được tạo",
    "Unable to delete user.": "Không thể xóa người dùng.",
    "Forbidden": "Bị cấm",
    "Invalid user": "Người dùng không hợp lệ",
    "Unable to change mail address": "Không thể thay đổi địa chỉ hòm thư",
    "Email saved": "Đã lưu email",
    "Your full name has been changed.": "Họ tên của bạn đã được thay đổi.",
    "Unable to change full name": "Không thể thay đổi họ tên",
    "APCu": "APCu",
    "Redis": "Chương trình hỗ trợ lưu dữ liệu Redis",
    "Security & setup warnings": "Bảo mật và cảnh báo thiết lập",
    "Sharing": "Chia sẻ  ",
    "Server-side encryption": "Mã khóa phía máy chủ",
    "External Storage": "Bộ nhớ ngoài",
    "Cron": "Tiện ích nền cron",
    "Email server": "Máy chủ email",
    "Log": "Đăng nhập",
    "Tips & tricks": "Mẹo & thủ thuật",
    "Updates": "Cập nhật",
    "Couldn't remove app.": "Không thể loại bỏ ứng dụng",
    "Language changed": "Ngôn ngữ đã thay đổi",
    "Invalid request": "Yêu cầu không hợp lệ",
    "Admins can't remove themself from the admin group": "Quản trị viên không thể loại bỏ chính mình khỏi nhóm quản trị",
    "Unable to add user to group %s": "Không thể thêm người dùng vào nhóm %s",
    "Unable to remove user from group %s": "Không thể loại bỏ người dùng khỏi nhóm %s",
    "Couldn't update app.": "Không thể cập nhật ứng dụng",
    "Are you really sure you want add \"{domain}\" as trusted domain?": "Bạn có thực sự chắc chắn muốn thêm \"{domain}\" là miền được ủy thác?",
    "Add trusted domain": "Thêm miền ủy thác",
    "Migration in progress. Please wait until the migration is finished": "Đang thực hiện di chuyển. Vui lòng đợi đến khi việc di chuyển hoàn tất",
    "Migration started …": "Bắt đầu di chuyển…",
    "Sending...": "Đang gửi...",
    "Official": "Chính thức",
    "Approved": "Được công nhận",
    "Experimental": "Thử nghiệm",
    "All": "Tất cả",
    "No apps found for your version": "Không tìm thấy ứng dụng cho phiên bản của bạn",
    "The app will be downloaded from the app store": "Ứng dụng sẽ được tải từ kho ứng dụng",
    "Official apps are developed by and within the ownCloud community. They offer functionality central to ownCloud and are ready for production use.": true,
    "Approved apps are developed by trusted developers and have passed a cursory security check. They are actively maintained in an open code repository and their maintainers deem them to be stable for casual to normal use.": true,
    "This app is not checked for security issues and is new or known to be unstable. Install at your own risk.": "Ứng dụng này chưa được kiểm tra bảo mật và là mới hoặc được xác định là không ổn định. Cài đặt sẽ gây nguy hại cho bạn.",
    "Update to %s": "Cập nhật cho %s",
    "_You have %n app update pending_::_You have %n app updates pending_": "_Bạn có %n bản cập nhật ứng dụng đang chờ_::_Bạn có %n các bản cập nhật ứng dụng đang chờ_",
    "Please wait....": "Vui lòng đợi…",
    "Error while disabling app": "Lỗi khi tắt ứng dụng",
    "Disable": "Tắt",
    "Enable": "Kích hoạt",
    "Error while enabling app": "Lỗi khi kích hoạt ứng dụng",
    "Error: this app cannot be enabled because it makes the server unstable": "Lỗi: ứng dụng này không thể được kích hoạt vì chúng làm máy chủ không ổn định",
    "Error: could not disable broken app": "Lỗi: không thể tắt ứng dụng bị hỏng",
    "Error while disabling broken app": "Lỗi khi tắt ứng dụng bị hỏng",
    "Updating....": "Đang cập nhật…",
    "Error while updating app": "Lỗi khi cập nhật ứng dụng",
    "Updated": "Đã cập nhật",
    "Uninstalling ....": "Đang gỡ cài đặt…",
    "Error while uninstalling app": "Lỗi khi gỡ cài đặt ứng dụng",
    "Uninstall": "Gỡ cài đặt ",
    "The app has been enabled but needs to be updated. You will be redirected to the update page in 5 seconds.": "Ứng dụng này đã được kích hoạt nhưng cần cập nhật. Bạn sẽ được chuyển hướng sang trang cập nhật trong 5 giây.",
    "App update": "Cập nhật ứng dụng",
    "No apps found for {query}": "Không tìm thấy ứng dụng cho {query}",
    "Disconnect": "Ngưng kết nối",
    "Error while loading browser sessions and device tokens": "Lỗi khi tải phiên trình duyệt và mã thông báo của thiết bị",
    "Error while creating device token": "Lỗi khi tạo mã thông báo của thiết bị",
    "Error while deleting the token": "Lỗi khi xóa mã thông báo",
    "An error occurred. Please upload an ASCII-encoded PEM certificate.": "Có lỗi xảy ra. Vui lòng tải lên tập tin chứng thực PEM chuẩn mã ASCII",
    "Valid until {date}": "Hợp lệ cho đến {date}",
    "Delete": "Xóa",
    "An error occurred: {message}": "Có lỗi xảy ra: {message}",
    "Select a profile picture": "Chọn hình đại diện",
    "Very weak password": "Mật khẩu rất yếu",
    "Weak password": "Mật khẩu yếu",
    "So-so password": "Mật khẩu bình thường",
    "Good password": "Mật khẩu tốt",
    "Strong password": "Mật khẩu mạnh",
    "Groups": "Nhóm",
    "Unable to delete {objName}": "Không thể xóa {objName}",
    "Error creating group: {message}": "Lỗi tạo nhóm: {message}",
    "A valid group name must be provided": "Phải cung cấp tên nhóm hợp lệ",
    "deleted {groupName}": "đã xóa {groupName}",
    "undo": "hoàn tác",
    "no group": "không có nhóm",
    "never": "không bao giờ",
    "deleted {userName}": "đã xóa {userName}",
    "add group": "thêm nhóm",
    "Changing the password will result in data loss, because data recovery is not available for this user": "Thay đổi mật khẩu sẽ gây ra mất dữ liệu, vì chức năng khôi phục dữ liệu ",
    "A valid username must be provided": "Phải cung cấp tên người dùng hợp lệ",
    "Error creating user: {message}": "Lỗi tạo người dùng: {message}",
    "A valid password must be provided": "Phải cung cấp mật khẩu hợp lệ",
    "A valid email must be provided": "Phải cung cấp địa chỉ email hợp lệ",
    "__language_name__": "__language_name__",
    "Unlimited": "Không giới hạn",
    "Personal info": "Thông tin cá nhân",
    "Sessions": "Phiên",
    "App passwords": "Mật khẩu ứng dụng",
    "Sync clients": "Đồng bộ khách hàng",
    "Everything (fatal issues, errors, warnings, info, debug)": "Tất cả (vấn đề nguy hại, lỗi, cảnh báo, thông tin, sửa lỗi)",
    "Info, warnings, errors and fatal issues": "Thông tin, cảnh bảo, lỗi và vấn đề nguy hại",
    "Warnings, errors and fatal issues": "Cảnh báo, lỗi và vấn đề nguy hại",
    "Errors and fatal issues": "Lỗi và vấn đề nguy hại",
    "Fatal issues only": "Chỉ riêng vấn đề nguy hại",
    "None": "Không",
    "Login": "Đăng nhập",
    "Plain": "Thuần túy",
    "NT LAN Manager": "Quản lý NT LAN",
    "SSL": "SSL",
    "TLS": "TLS",
    "php does not seem to be setup properly to query system environment variables. The test with getenv(\"PATH\") only returns an empty response.": true,
    "Please check the <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">installation documentation ↗<\/a> for php configuration notes and the php configuration of your server, especially when using php-fpm.": true,
    "The Read-Only config has been enabled. This prevents setting some configurations via the web-interface. Furthermore, the file needs to be made writable manually for every update.": true,
    "PHP is apparently setup to strip inline doc blocks. This will make several core apps inaccessible.": true,
    "This is probably caused by a cache\/accelerator such as Zend OPcache or eAccelerator.": true,
    "Your database does not run with \"READ COMMITED\" transaction isolation level. This can cause problems when multiple actions are executed in parallel.": true,
    "Your server is running on Microsoft Windows. We highly recommend Linux for optimal user experience.": true,
    "%1$s below version %2$s is installed, for stability and performance reasons we recommend updating to a newer %1$s version.": true,
    "The PHP module 'fileinfo' is missing. We strongly recommend to enable this module to get best results with mime-type detection.": true,
    "Transactional file locking is disabled, this might lead to issues with race conditions. Enable 'filelocking.enabled' in config.php to avoid these problems. See the <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">documentation ↗<\/a> for more information.": true,
    "System locale can not be set to a one which supports UTF-8.": true,
    "This means that there might be problems with certain characters in file names.": true,
    "We strongly suggest installing the required packages on your system to support one of the following locales: %s.": true,
    "If your installation is not installed in the root of the domain and uses system cron, there can be issues with the URL generation. To avoid these problems, please set the \"overwrite.cli.url\" option in your config.php file to the webroot path of your installation (Suggested: \"%s\")": true,
    "It was not possible to execute the cronjob via CLI. The following technical errors have appeared:": true,
    "Please double check the <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">installation guides ↗<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>.": true,
    "All checks passed.": "Tất cả đã qua kiểm tra",
    "Open documentation": "Tài liệu mở",
    "Allow apps to use the Share API": "Cho phép ứng dụng sử dụng trình Share API",
    "Allow users to share via link": "Cho phép người dùng chia sẻ liên kết ",
    "Allow public uploads": "Cho phép tải lên công khai",
    "Enforce password protection": "Thực thi bảo vệ mật khẩu",
    "Set default expiration date": "Thiết lập ngày hết hạn mặc định",
    "Allow users to send mail notification for shared files": "Cho phép người dùng gửi thư thông báo với các tập tin chia sẻ",
    "Expire after": "Hết hạn sau ",
    "days": "ngày",
    "Enforce expiration date": "Thực thi ngày hết hạn",
    "Allow resharing": "Cho phép chia sẻ lại",
    "Allow sharing with groups": "Cho phép chia sẻ với nhóm",
    "Restrict users to only share with users in their groups": "Hạn chế người dùng chỉ chia sẻ với người dùng trong nhóm của họ",
    "Allow users to send mail notification for shared files to other users": "Cho phép người dùng gửi thư thông báo cho tập tin được chia sẻ đến người dùng khác",
    "Exclude groups from sharing": "Rút nhóm ra khỏi việc chia sẻ",
    "These groups will still be able to receive shares, but not to initiate them.": "Nhóm này sẽ vẫn có thể nhận chia sẻ, nhưng không thể khởi động chúng.",
    "Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.": "Cho phép tự động hoàn thiện tên người dùng trong hội thoại chia sẻ. Nếu nó không được kích hoạt, cần phải nhập họ tên người dùng.",
    "Last cron job execution: %s.": "Thực hiện công việc định kỳ gần nhất: %s.",
    "Last cron job execution: %s. Something seems wrong.": "Thực hiện công việc định kỳ gần nhất: %s. Đã có lỗi.",
    "Cron was not executed yet!": "Công việc định kỳ vẫn chưa được thực hiện!",
    "Execute one task with each page loaded": "Thực hiện một nhiệm vụ cho mỗi trang được tải",
    "cron.php is registered at a webcron service to call cron.php every 15 minutes over http.": "cron.php được đăng ký cho dịch vụ định kỳ web để gọi cron.php mỗi chu kỳ 15 phút qua http.",
    "Use system's cron service to call the cron.php file every 15 minutes.": "Sử dụng dịch vụ định kỳ của hệ thống để gọi tập tin cron.php mỗi 15 phút.",
    "Enable server-side encryption": "Kích hoạt mã hóa phía máy chủ",
    "Please read carefully before activating server-side encryption:": "Vui lòng đọc kỹ trước khi kích hoạt mã hóa phía máy chủ",
    "Once encryption is enabled, all files uploaded to the server from that point forward will be encrypted at rest on the server. It will only be possible to disable encryption at a later date if the active encryption module supports that function, and all pre-conditions (e.g. setting a recover key) are met.": true,
    "Encryption alone does not guarantee security of the system. Please see ownCloud documentation for more information about how the encryption app works, and the supported use cases.": true,
    "Be aware that encryption always increases the file size.": "Hãy chú ý rằng mã hóa luôn luôn làm tăng kích thước tập tin.",
    "It is always good to create regular backups of your data, in case of encryption make sure to backup the encryption keys along with your data.": true,
    "This is the final warning: Do you really want to enable encryption?": "Đây là cảnh báo cuối cùng: Bạn có thực sự muốn cho phép mã hóa?",
    "Enable encryption": "Cho phép mã hóa",
    "No encryption module loaded, please enable an encryption module in the app menu.": "Không tải được môđun mã hóa, vui lòng kích hoạt môđun mã hóa trong menu ứng dụng.",
    "Select default encryption module:": "Chọn môđun mã hóa mặc định: ",
    "You need to migrate your encryption keys from the old encryption (ownCloud <= 8.0) to the new one. Please enable the \"Default encryption module\" and run 'occ encryption:migrate'": true,
    "You need to migrate your encryption keys from the old encryption (ownCloud <= 8.0) to the new one.": "Bạn cần phải di chuyển các chìa khóa mã hóa của bạn từ mã hóa cũ (ownCloud <= 8,0) sang mới.",
    "Start migration": "Bắt đầu di chuyển",
    "This is used for sending out notifications.": "Điều này được dùng để gửi thông báo.",
    "Send mode": "Chế độ gửi",
    "Encryption": "Mã hóa",
    "From address": "Từ địa chỉ",
    "mail": "thư",
    "Authentication method": "Phương pháp xác thực",
    "Authentication required": "Yêu cầu xác thực",
    "Server address": "Địa chỉ máy chủ",
    "Port": "Cổng",
    "Credentials": "Thông tin",
    "SMTP Username": "Tên người dùng SMTP",
    "SMTP Password": "Mật khẩu SMTP",
    "Store credentials": "Thông tin lưu trữ",
    "Test email settings": "Thiết lập thông tin thử nghiệm",
    "Send email": "Gửi email",
    "Download logfile": "Tải xuống tập tin đăng nhập",
    "More": "Hơn",
    "Less": "Kém",
    "The logfile is bigger than 100 MB. Downloading it may take some time!": "Tập tin đăng nhập lớn hơn 100 MB. Tải xuống sẽ tốn chút thời gian!",
    "What to log": "Đăng nhập cái gì",
    "SQLite is used as database. For larger installations we recommend to switch to a different database backend.": "SQLite được dùng làm cơ sở dữ liệu. Để cài đặt dung lượng lớn hơn chúng tôi khuyên bạn nên chuyển sang bản sao lưu cơ sở dữ liệu.",
    "Especially when using the desktop client for file syncing the use of SQLite is discouraged.": "Đặc biệt khi sử dụng màn hình khách để đồng bộ tập tin nên sử dụng SQLite.",
    "To migrate to another database use the command line tool: 'occ db:convert-type', or see the <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">documentation ↗<\/a>.": true,
    "How to do backups": "Sao lưu như thế nào",
    "Advanced monitoring": "Kiểm soát nâng cao",
    "Performance tuning": "Điều chỉnh hiệu năng",
    "Improving the config.php": "Cải thiện config.php",
    "Theming": "Chủ đề",
    "Hardening and security guidance": "Hướng dẫn làm cứng và bảo mật",
    "Version": "Phiên bản",
    "Developer documentation": "Tài liệu nhà pháp triển",
    "Experimental applications ahead": "Ứng dụng thử nghiệm phía trước",
    "Experimental apps are not checked for security issues, new or known to be unstable and under heavy development. Installing them can cause data loss or security breaches.": true,
    "by %s": "bởi %s",
    "%s-licensed": "%s-được cấp phép",
    "Documentation:": "Tài liệu:",
    "User documentation": "Tài liệu người dùng",
    "Admin documentation": "Tài liệu quản trị",
    "Visit website": "Thăm trang web",
    "Report a bug": "Báo lỗi",
    "Show description …": "Hiển thị mô tả…",
    "Hide description …": "Ẩn mô tả…",
    "This app has an update available.": "Ứng dụng này có sẵn bản cập nhật.",
    "This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.": "Ứng dụng này không có phiên bản ownCloud tối thiểu. Sẽ xảy ra lỗi với ownCloud 11 hoặc cao hơn.",
    "This app has no maximum ownCloud version assigned. This will be an error in ownCloud 11 and later.": "Ứng dụng này không có phiên bản ownCloud tối đa. Sẽ xảy ra lỗi với ownCloud 11 hoặc cao hơn.",
    "This app cannot be installed because the following dependencies are not fulfilled:": "Không thể cài đặt ứng dụng này vì các điều kiện đi kèm sau không được thỏa mãn:",
    "Enable only for specific groups": "Chỉ cho phép các nhóm nhất định",
    "Uninstall App": "Gỡ cài đặt ứng dụng",
    "Enable experimental apps": "Cho phép ứng dụng thử nghiệm",
    "SSL Root Certificates": "Chứng chỉ Gốc SSL",
    "Common Name": "Tên thông dụng",
    "Valid until": "Hợp lệ từ",
    "Issued By": "Được giải quyết bởi",
    "Valid until %s": "Hợp lệ từ %s",
    "Import root certificate": "Nhập chứng chỉ gốc",
    "Hey there,<br><br>just letting you know that you now have an %s account.<br><br>Your username: %s<br>Access it: <a href=\"%s\">%s<\/a><br><br>": true,
    "Cheers!": "Chúc mừng!",
    "Hey there,\n\njust letting you know that you now have an %s account.\n\nYour username: %s\nAccess it: %s": "Xin chào, chỉ để bạn biết rằng bạn hiện có %s tài khoản. Tên người dùng của bạn: %s Truy cập tại: %s",
    "Administrator documentation": "Tài liệu quản trị viên",
    "Online documentation": "Tài liệu trực tuyến",
    "Forum": "Diễn đàn",
    "Issue tracker": "Người theo dõi vấn đề",
    "Commercial support": "Hỗ trợ thương mại",
    "You are using <strong>%s<\/strong> of <strong>%s<\/strong>": "Bạn đang sử dụng <strong>%s<\/strong> của <strong>%s<\/strong>",
    "Profile picture": "Hình hồ sơ",
    "Upload new": "Tải lên mới",
    "Select from Files": "Chọn từ các tập tin",
    "Remove image": "Bỏ hình ảnh",
    "png or jpg, max. 20 MB": "png hoặc jpg, tối đa 20 MB",
    "Picture provided by original account": "Hình theo tài khoản gốc",
    "Cancel": "Hủy",
    "Choose as profile picture": "Chọn là hình hồ sơ",
    "Full name": "Họ và tên",
    "No display name set": "Không hiển thị thiết lập tên",
    "Email": "Email",
    "Your email address": "Địa chỉ email của bạn",
    "For password recovery and notifications": "Để khôi phục mật khẩu và thông báo",
    "No email address set": "Không có thiết lập email",
    "You are member of the following groups:": "Bạn là thành viên của nhóm sau:",
    "Password": "Mật khẩu",
    "Unable to change your password": "Không thể thay đổi mật khẩu của bạn",
    "Current password": "Mật khẩu hiện tại",
    "New password": "Mật khẩu mới",
    "Change password": "Thay đổi mật khẩu",
    "Language": "Ngôn ngữ",
    "Help translate": "Giúp dịch",
    "These are the web, desktop and mobile clients currently logged in to your ownCloud.": "Đây là trang web màn hình và điện thoại khách hiện đăng nhập vào ownCloud của bạn.",
    "Browser": "Trình duyệt",
    "Most recent activity": "Hoạt động gần nhất",
    "You've linked these apps.": "Bạn đã  liên kết với ứng dụng này.",
    "Name": "Tên",
    "An app password is a passcode that gives an app or device permissions to access your %s account.": "Mật khẩu ứng dụng là một mã mật khẩu cho phép ứng dụng hoặc thiết bị truy cập vào tài khoản %s.",
    "App name": "Tên ứng dụng",
    "Create new app password": "Tạo mật khẩu ứng dụng mới",
    "Use the credentials below to configure your app or device.": "Sử dụng thông tin dưới để cấu hình ứng dụng hoặc thiết bị của bạn.",
    "Username": "Tên người dùng",
    "Done": "Đã xong",
    "Get the apps to sync your files": "Dùng ứng dụng để đồng bộ tập tin của bạn",
    "Desktop client": "Màn hình khách",
    "Android app": "Ứng dụng Android",
    "iOS app": "Ứng dụng iOS",
    "If you want to support the project\n\t\t<a href=\"https:\/\/owncloud.org\/contribute\"\n\t\t\ttarget=\"_blank\" rel=\"noreferrer\">join development<\/a>\n\t\tor\n\t\t<a href=\"https:\/\/owncloud.org\/promote\"\n\t\t\ttarget=\"_blank\" rel=\"noreferrer\">spread the word<\/a>!": "Nếu bạn muốn hỗ trợ dự án này <a href=\"https:\/\/owncloud.org\/contribute\"target=\"_blank\" rel=\"noreferrer\"> tham gia phát triển <\/a> hoặc <atarget=\"_blank\" rel=\"noreferrer\"> thông báo <\/a>!",
    "Show First Run Wizard again": "Hiển thị lại Wizard Chạy lần đầu",
    "Developed by the {communityopen}ownCloud community{linkclose}, the {githubopen}source code{linkclose} is licensed under the {licenseopen}<abbr title=\"Affero General Public License\">AGPL<\/abbr>{linkclose}.": true,
    "Show storage location": "Hiển thị vị trí bộ nhớ",
    "Show last log in": "Hiển thị lần đăng nhập cuối",
    "Show user backend": "Hiển thị sao lưu của người dùng",
    "Send email to new user": "Gửi email đến người dùng mới",
    "Show email address": "Hiển thị địa chỉ email",
    "E-Mail": "E-Mail",
    "Create": "Tạo",
    "Admin Recovery Password": "Mật khẩu khôi phục quản trị",
    "Enter the recovery password in order to recover the users files during password change": "Nhập mật khẩu khôi phục để khôi phục tập tin người dùng khi thay đổi mật khẩu",
    "Add Group": "Thêm nhóm",
    "Group": "Nhóm",
    "Everyone": "Mọi người",
    "Admins": "Quản trị viên",
    "Default Quota": "Hạn ngạch mặc định",
    "Please enter storage quota (ex: \"512 MB\" or \"12 GB\")": "Vui lòng nhập hạn ngạch bộ nhớ (ví dụ: \"512 MB\" hoặc \"12 GB\")",
    "Other": "Khác",
    "Full Name": "Họ và tên",
    "Group Admin for": "Nhóm quản trị viên cho",
    "Quota": "Hạn ngạch  ",
    "Storage Location": "Vị trí bộ nhớ",
    "User Backend": "Sao lưu người dùng",
    "Last Login": "Lần đăng nhập cuối",
    "change full name": "thay đổi họ tên",
    "set new password": "thiết lập mật khẩu mới",
    "change email address": "thay đổi địa chỉ email"
},"nplurals=1; plural=0;");
